name: 🚀 Deploy PHP via FTP

on:
  push:
    branches:
      - main   # jab bhi main branch pe push hoga, deploy trigger hoga

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 📤 Deploy to Server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./            # kaunsa folder upload karna hai (root)
          server-dir: /note4.mukeshkumarmajhi.com.np/htdocs/   # server pe kis folder me daalna hai
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env