name: 🚀 Deploy to InfinityFree via FTP

on:
  push:
    branches:
      - main   # jab bhi main branch pe push hoga, ye chalega

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Create .env file from secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: 📤 Deploy to InfinityFree via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /note4.mukeshkumarmajhi.com.np/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/README.md